name: Property Sales
backend: postgres
db: etl
table: assessor.sales_joined
epsg: 4326
description: >
  Parcel sales history.
disclaimer: >
website: https://cityofdetroit.github.io/data-resources/datasets/
updates_every: day
license:
agency: Assessor's Office
attribution:
source_link:
image:
contact:
  email: iet@detroitmi.gov
  name: IET Team
socrata:
  id: xbvp-4is5
  view: assessor.sales_socrata
  category: "Property & Parcels"
  tags:
    - sales
    - history
    - assessor
    - parcel
  row_identifier: id
  permission: public
  # column mapping, used by the create script
  columns:
    id:
      expression: id
      human: id
      type: number
    parcel_no:
      expression: parcel_no
      human: parcel_no
      type: text
    sale_date:
      expression: concat(replace(sale_date::text, ' ', 'T'), 'Z')
      human: sale_date
      type: calendar_date
    sale_price:
      expression: case when sale_price is null then null else sale_price end
      human: sale_price
      type: money
    terms:
      expression: terms
      human: terms
      type: text
    instrument:
      expression: instrument
      human: instrument
      type: text
    grantor:
      expression: grantor
      human: grantor
      type: text
    grantee:
      expression: grantee
      human: grantee
      type: text
    address:
      expression: address
      human: address
      type: text
    location:
      expression: case when wkb_geometry is not null then concat('location ( ',st_x(st_transform(st_centroid(wkb_geometry), 4326)),', ',st_y(st_transform(st_centroid(wkb_geometry), 4326)),' )') else null end
      human: location
      type: location
  # not automatable
  row_label: Property Sale
  time_period: 