name: City of Detroit Contracts
backend: postgres
db: etl
table: ocp
description: >
  This dataset includes open contracts between the City of Detroit and its suppliers. 
  Contracts are sorted by NIGP Code, an industry standard for classifying services and products procured by government organizations. 
  This dataset does not include contracts for personal services between the City and individuals, closed or historical contracts, 
  contracts less than $25k, or contracts with the Detroit Water and Sewerage Department (DWSD). 
  When possible, a link to the original contract document is provided. This data updates nightly Monday-Friday.
disclaimer: >
  This data includes initial and amended contracts with suppliers. Purchase orders may be generated separately to pay suppliers for work
  completed under one of the contracts listed in this dataset.
website: https://cityofdetroit.github.io/data-resources/datasets/
updates_every: day
license: Public Domain
agency: Office of Contracting and Procurement (OCP)
attribution: Office of Contracting and Procurement (OCP)
source_link:
image:
contact:
  email: iet@detroitmi.gov
  name: IET Team
socrata:
  id: itv9-b6jk
  view: ocp_socrata
  category: Government
  tags:
    - contracts
    - suppliers
    - finance
    - procurement
  row_identifier: contract_contract_id
  permission: private
  columns:
    contract_nigp_code:
      expression: contract_nigp_code
      human: Contract NIGP Code
      type: text
    contract_contract_id:
      expression: contract_contract_id
      human: Contract ID
      type: text
    company_company_name:
      expression: company_company_name
      human: Company Name
      type: text
    company_city:
      expression: company_city
      human: Company City
      type: text
    company_state:
      expression: company_state
      human: Company State
      type: text
    contract_contract_purpose:
      expression: contract_contract_purpose
      human: Contract Purpose
      type: text
    contract_value:
      expression: contract_value
      human: Contract Amount
      type: money
    contract_effective_date:
      expression: contract_effective_date
      human: Contract Effective Date
      type: calendar_date
    contract_contract_expiration_date:
      expression: contract_contract_expiration_date
      human: Contract Expiration Date
      type: calendar_date
    contract_status:
      expression: contract_status
      human: Contract Status
      type: text
    contract_contract_agreement_type:
      expression: contract_contract_agreement_type
      human: Contract Agreement Type
      type: text
    contract_document:
      expression: contract_document
      human: Contract Document Link
      type: text
  row_label: Contract
  time_period:
