name: DPD - All Crime Incidents, December 6, 2016 - Present (Private View)
backend: postgres
db: etl
table: rms_daily
description: >
  This private view follows the same data processing and location anonymization methods as https://data.detroitmi.gov/Public-Safety/DPD-All-Crime-Incidents-December-6-2016-Present/6gdg-y3kf, except that this view updates nightly rather than by IBR report date.
disclaimer: >
  See Disclaimer at: https://data.detroitmi.gov/Public-Safety/DPD-All-Crime-Incidents-December-6-2016-Present/6gdg-y3kf
website: https://cityofdetroit.github.io/data-resources/datasets/
updates_every: day
license:
agency: Detroit Police Department
attribution:
source_link:
image:
contact:
  email: crimeintelligencebureau@detroitmi.gov
  name: Crime Intelligence Unit
socrata:
  id:
  api_id:
  view: rms_daily_socrata
  category: Public Safety
  tags:
    - police
    - dpd
    - "911"
    - "calls for service"
  row_identifier: uniq
  permission: private
  # column mapping, used by the create script
  columns:
    uniq:
      expression: uniq
      human: Unique ID
      type: number
    crime_id:
      expression: dpdcrimeid
      human: Crime ID
      type: text
    report_number:
      expression: report_number
      human: "Report #"
      type: text
    address:
      expression: address
      human: "Incident Address"
      type: text
    offense_description:
      expression: offense_description
      human: Offense Description
      type: text
    offense_category:
      expression: offense_category
      human: Offense Category
      type: text
    state_offense_code:
      expression: state_offense_code
      human: State Offense Code
      type: text
    incident_timestamp:
      expression: replace(to_char(concat(incident_date, ' ', left(incident_time, 2), ':', right(incident_time, 2), ':00')::timestamp, 'YYYY-MM-DD HH24:MI:SS.000'), ' ', 'T')
      human: Incident Date & Time
      type: calendar_date
    incident_time:
      expression: incident_time
      human: Incident Time (24h)
      type: text
    day_of_week:
      expression: extract(dow from concat(incident_date, ' ', left(incident_time, 2), ':', right(incident_time, 2), ':00')::timestamp) + 1
      human: Day of Week (Sunday is 1)
      type: number
    hour_of_day:
      expression: left(incident_time, 2)::integer
      human: Hour of Day
      type: number
    year:
      expression: right(incident_date, 4)::integer
      human: Year
      type: number
    scout_car_area:
      expression: scout_car_area
      human: Scout Car Area
      type: text
    precinct:
      expression: precinct
      human: Precinct Number
      type: text
    block_id:
      expression: block_id
      human: Census Block GEOID
      type: text
    neighborhood:
      expression: neighborhood
      human: Neighborhood
      type: text
    council_district:
      expression: council_district
      human: Council District
      type: text
    zip_code:
      expression: zip_code
      human: Zip Code
      type: text
    longitude:
      expression: lon
      human: Longitude
      type: number
    latitude:
      expression: lat
      human: Latitude
      type: number
    # ibr_date:
    #   expression: replace(to_char(ibr_date::timestamp, 'YYYY-MM-DD HH24:MI:SS.000'), ' ', 'T')
    #   human: IBR Report Date
    #   type: calendar_date
    location:
      expression: CASE WHEN lat is null THEN null ELSE concat('location (', lat, ',', lon, ')') END
      human: Location
      type: location
  row_label: Incident
  time_period:
