name: Parcel Points Ownership
backend: postgres
db: etl
table: assessor.joined
epsg: 2898
description: >
  Parcel point file with ownership, assessment, and taxable value information. If you need the shapefiles, go to this dataset: https://data.detroitmi.gov/Property-Parcels/Parcel-Map/fxkw-udwfdisclaimer: >
website: https://cityofdetroit.github.io/data-resources/datasets/
updates_every: day
license:
agency: Assessors Division
attribution:
source_link:
image:
contact:
  email: iet@detroitmi.gov
  name: IET
mapbox:
  slug: parcel_points
  view: assessor.joined
  columns:
    - ST_Centroid(wkb_geometry) as wkb_geometry
    - parcelno
    - propaddr
    - taxpayer1
    - saledate
    - saleprice
socrata:
  id: dxgi-9s8s
  api_id: 
  view: parcel_points_ownership
  category: "Property & Parcels"
  tags:
    - parcels
    - assess
    - owner
    - tax
    - value
    - address
    - location
  row_identifier: objectid
  permission: public
  # column mapping, used by the create script
  columns:
    objectid:
      expression: objectid
      human: ObjectID
      type: number
    parcelnum:
      expression: parcelnum
      human: Parcel Number
      type: text
    address:
      expression: address
      human: Address
      type: text
    zip_code:
      expression: zip_code
      human: Zip Code
      type: text
    council_district:
      expression: council_district
      human: Council District
      type: text
    zoning:
      expression: zoning_rev
      human: Zoning
      type: text
    owner1:
      expression: owner1
      human: Owner
      type: text
    owner2:
      expression: owner2
      human: Owner 2
      type: text
    taxpayer:
      expression: taxpayer_name
      human: Taxpayer
      type: text
    owner_street:
      expression: owner_street
      human: Owner Street Address
      type: text
    owner_city:
      expression: owner_city
      human: Owner City
      type: text
    owner_state: 
      expression: owner_state
      human: Owner State
      type: text
    owner_zip: 
      expression: owner_zip
      human: Owner Zip Code
      type: text
    owner_country:
      expression: owner_country
      human: Owner Country
      type: text
    last_sale_date:
      expression: replace(to_char(last_sale_date, 'YYYY-MM-DD HH24:MI:SS.000'), ' ', 'T') 
      human: SaleDate
      type: calendar_date
    last_sale_price:
      expression: case when null then null else last_sale_price end
      human: Last Sale Price
      type: money
    last_terms_of_sale:
      expression: last_terms_of_sale
      human: Last Terms of Sale
      type: text
    estimated_true_cash_value:
      expression: estimated_true_cash_value
      human: Est. True Cash Value
      type: number
    land_value:
      expression: land_value
      human: Land Value
      type: number
    land_assessed_value:
      expression: land_assessed_value
      human: Land Assessed Value
      type: number
    building_assessed_value:
      expression: building_assessed_value
      human: Building Assessed Value
      type: number
    assessed_value:
      expression: assessed_value
      human: Total Assessed Value
      type: number
    taxable_value:
      expression: taxable_value
      human: Taxable Value
      type: number
    improved_value:
      expression: improved_value
      human: Improved Value
      type: number
    sev:
      expression: sev
      human: State Equalized Value
      type: number
    pre:
      expression: pre
      human: Principal Residence Exemption
      type: number
    property_class:
      expression: property_class
      human: Property Class
      type: text
    total_acres:
      expression: total_acres
      human: Total Acreage
      type: number
    frontage:
      expression: frontage
      human: Frontage
      type: number
    depth:
      expression: depth
      human: Depth
      type: number
    year_built:
      expression: year_built
      human: Year Built
      type: text
    num_buildings:
      expression: num_buildings
      human: Number of Buildings
      type: number
    num_stories:
      expression: num_stories
      human: Number of Stories
      type: number
    legaldesc:
      expression: legaldesc
      human: Legal Description
      type: text
    latitude:
      expression: st_y(st_centroid(st_transform(wkb_geometry, 4326)))
      human: Latitude
      type: number
    longitude:
      expression: st_x(st_centroid(st_transform(wkb_geometry, 4326)))
      human: Longitude
      type: number
    location:
      expression: concat('location(', st_y(st_centroid(st_transform(wkb_geometry, 4326))), ',' , st_x(st_centroid(st_transform(wkb_geometry, 4326))), ')')
      human: Location
      type: location
  row_label: Parcel
  time_period:
