name: Blight Violations
backend: postgres
db: etl
table: dah_bvn
epsg: 4326
description: >
  This dataset shows Blight Violation Notices (BVN), or Blight Tickets, that have been issued to property owners who have violated City of Detroit ordinances that govern how property owners must maintain 
  the exterior of their property. Blight Tickets are issued by city inspectors, police officers, neighborhood city hall managers and other city officials 
  who investigate complaints of blight and are managed by the Department of Administrative Hearings.
disclaimer: >
website: https://cityofdetroit.github.io/data-resources/datasets/
updates_every: day
license: Public Domain
agency: DAH
attribution:
source_link:
image:
contact:
  email: iet@detroitmi.gov
  name: IET Team
esri:
  slug: blight_notices
  view: dah_bvn_socrata
  columns:
    - ST_SetSRID(ST_MakePoint(longitude, latitude),4326) as wkb_geometry
    - '*'
mapbox:
  slug: blight_notices
  view: dah_bvn_socrata
  columns:
    - ST_SetSRID(ST_MakePoint(longitude, latitude),4326) as wkb_geometry
    - ticket_id
    - violator_name
    - violation_address
    - violation_code
    - judgment_amount
    - payment_amount
    - disposition
    - balance_due
socrata:
  id: ti6p-wcg4
  view: dah_bvn_socrata
  category: "Property & Parcels"
  tags:
    - blight
    - violations
  row_identifier: ticket_id
  permission: private
  # column mapping, used by the create script
  columns:
    ticket_id:
      expression: ticket_id
      human: Ticket ID
      type: number
    ticket_number:
      expression: ticket_number
      human: Ticket Number
      type: text
    agency_name:
      expression: agency_name
      human: Agency Name
      type: text
    inspector_name:
      expression: inspector_name
      human: Inspector Name
      type: text
    violator_name:
      expression: violator_name
      human: Violator Name
      type: text
    violator_id:
      expression: violator_id
      human: Violator ID
      type: number
    violation_street_number:
      expression: violation_street_number
      human: Violation Street Number
      type: text
    violation_street_name:
      expression: violation_street_name
      human: Violation Street Name
      type: text
    violation_zip_code:
      expression: violation_zip_code
      human: Violation Zip Code
      type: text
    mailing_address_str_number:
      expression: mailing_address_str_number
      human: Mailing Address Street Number
      type: text
    mailing_address_str_name:
      expression: mailing_address_str_name
      human: Mailing Address Street Name
      type: text
    city:
      expression: city
      human: Mailing Address City
      type: text
    state:
      expression: state
      human: Mailing Address State
      type: text
    zip_code:
      expression: zip_code
      human: Mailing Address Zip Code
      type: text
    non_us_str_code:
      expression: non_us_str_code
      human: Mailing Address Non-USA Code
      type: text
    country:
      expression: country
      human: Mailing Address Country
      type: text
    violation_date:
      expression: replace(to_char(violation_date::timestamp, 'YYYY-MM-DD HH24:MI:SS.000'), ' ', 'T')
      human: Violation Date
      type: calendar_date
    ticket_issued_time:
      expression: right(ticket_issued_time, 8)
      human: Ticket Issued Time
      type: text
    hearing_date:
      expression: replace(to_char(hearing_date::timestamp, 'YYYY-MM-DD HH24:MI:SS.000'), ' ', 'T')
      human: Hearing Date
      type: calendar_date
    hearing_time:
      expression: hearing_time
      human: Hearing Time
      type: text
    violation_code:
      expression: violation_code
      human: Violation Code
      type: text
    violation_description:
      expression: violation_description
      human: Violation Description
      type: text
    disposition:
      expression: disposition
      human: Disposition
      type: text
    fine_amount:
      expression: CASE fine_amount WHEN 'NaN' THEN null ELSE fine_amount END
      human: Fine Amount
      type: money
    admin_fee:
      expression: CASE admin_fee WHEN 'NaN' THEN null ELSE admin_fee END
      human: Admin Fee
      type: money
    state_fee:
      expression: CASE state_fee WHEN 'NaN' THEN null ELSE state_fee END
      human: State Fee
      type: money
    late_fee:
      expression: CASE late_fee WHEN 'NaN' THEN null ELSE late_fee END
      human: Late Fee
      type: money
    discount_amount:
      expression: CASE discount_amount WHEN 'NaN' THEN null ELSE discount_amount END
      human: Discount Amount
      type: money
    clean_up_cost:
      expression: CASE clean_up_cost WHEN 'NaN' THEN null ELSE clean_up_cost END
      human: Clean Up Cost
      type: money
    judgment_amount:
      expression: CASE judgment_amount WHEN 'NaN' THEN null ELSE judgment_amount END
      human: Judgment Amount (Total Due)
      type: money
    payment_amount:
      expression: CASE payment_amount WHEN 'NaN' THEN null ELSE payment_amount END
      human: Payment Amount (Sum of All Payments)
      type: money
    balance_due: 
      expression: CASE balance_due WHEN 'NaN' THEN null ELSE balance_due END
      human: Balance Due
      type: money
    payment_date:
      expression: replace(to_char(payment_date::timestamp, 'YYYY-MM-DD HH24:MI:SS.000'), ' ', 'T')
      human: Payment Date (Most Recent)
      type: calendar_date
    payment_status:
      expression: payment_status
      human: Payment Status
      type: text
    collection_status:
      expression: collection_status
      human: Collection Status
      type: text
    violation_address:
      expression: violation_address
      human: Violation Address
      type: text
    parcelno:
      expression: parcelno
      human: Violation Parcel ID
      type: text
    latitude:
      expression: latitude
      human: Violation Latitude
      type: number
    longitude:
      expression: longitude
      human: Violation Longitude
      type: number
    location:
      expression: CASE WHEN latitude is null THEN null ELSE concat('location (', latitude, ',', longitude, ')') END
      human: Violation Location
      type: location
  # not automatable
  row_label: Ticket
  time_period:
  