name: DLBA Auctions Closed
backend: postgres
db: etl
table: dlba.auction_sold
description: >
  DLBA Auction Sales http://www.buildingdetroit.org/our-programs/auction-program/
disclaimer: >
website: https://cityofdetroit.github.io/data-resources/datasets/
updates_every: day
license:
agency: Detroit Land Bank Authority
attribution:
source_link:
image:
contact:
  email: iet@detroitmi.gov
  name: IET Team
socrata:
  id: tgwk-njih
  view: dlba.auction_sold_socrata
  category: "Property & Parcels"
  tags:
    - landbank
    - sold
    - auction
  row_identifier: parcel_id
  permission: public
  # column mapping, used by the create script
  columns:
    actual_closing_date:
      expression: concat_ws('T', actual_closing_date, '00:00:00.000Z')
      human: Closing Date
      type: calendar_date
    sale_status:
      expression: sale_status
      human: Sale Status
      type: text
    address:
      expression: address
      human: Address
      type: text
    parcel_id:
      expression: parcel_id
      human: Parcel ID
      type: text
    program:
      expression: program
      human: Program
      type: text
    neighborhood:
      expression: neighborhood
      human: Neighborhood
      type: text
    council_district:
      expression: council_district
      human: Council District
      type: number
    acct_latitude:
      expression: acct_latitude
      human: Latitude
      type: number
    acct_longitude:
      expression: acct_longitude
      human: Longitude
      type: number
    buyer_status:
      expression: buyer_status
      human: Buyer Status
      type: text
    final_sale_price:
      expression: CASE final_sale_price WHEN 'NaN' THEN null ELSE final_sale_price END
      human: Final Sale Price
      type: money
    purchaser_type:
      expression: purchaser_type
      human: Purchaser Type
      type: text
    location:
      expression: CASE WHEN acct_latitude is null THEN null ELSE concat('location (', acct_latitude, ',', acct_longitude, ')') END
      human: Location
      type: location
  # not automatable
  row_label: Auction Sale
  time_period: 
