name: DPD - All Crime Incidents, December 6, 2016 - Present
backend: postgres
db: etl
table: rms
description: >
  This data reflects reported criminal offenses that have occurred in the City of Detroit since December 6, 2016. Offense data was extracted from the Detroit Police Department's records management system. This data set contains the most recent data available and is updated anytime DPD sends official crime records contributing to the Michigan Incident Crime Reporting (MICR) or the National Incident Based Reporting systems (reflected by the IBR Date field). It should be noted that some incidents involve the commission of multiple offenses, such as a domestic assault where property was also vandalized. Accordingly, the data describe all offenses associated with all reported incidents.
disclaimer: >
  These data are based upon preliminary information supplied to the Police Department by the reporting parties and are subject to verification. The Detroit Police Department does not guarantee (either expressed or implied) the accuracy, completeness, timeliness, or correct sequencing of the information and the information should not be used for comparison purposes over time. The Detroit Police Department will not be responsible for any error or omission, or for the use of, or the results obtained from the use of this information. All data visualizations on maps should be considered approximate and attempts to derive specific addresses are strictly prohibited. The Detroit Police Department is not responsible for the content of any off-site pages that are referenced by or that reference this web page other than an official City of Detroit or Detroit Police Department web page. The user specifically acknowledges that the Detroit Police Department is not responsible for any defamatory, offensive, misleading, or illegal conduct of other users, links, or third parties and that the risk of injury from the foregoing rests entirely with the user. Any use of the information for commercial purposes is strictly prohibited. The unauthorized use of the words Detroit Police Department, "Detroit Police," or any colorable imitation of these words or the unauthorized use of the Detroit Police Department logo is unlawful. This web page does not, in any way, authorize such use.
website: https://cityofdetroit.github.io/data-resources/datasets/
updates_every: day
license:
agency: Detroit Police Department
attribution:
source_link:
image:
contact:
  email: crimeintelligencebureau@detroitmi.gov
  name: Crime Intelligence Unit
socrata:
  id: 6gdg-y3kf
  api_id: 
  view: rms_socrata
  category: Public Safety
  tags:
    - police
    - dpd
    - "911"
    - "calls for service"
  row_identifier: uniq
  permission: private
  # column mapping, used by the create script
  columns:
    uniq:
      expression: uniq
      human: Unique ID
      type: number
    crime_id:
      expression: dpdcrimeid
      human: Crime ID
      type: text
    report_number:
      expression: report_number
      human: "Report #"
      type: text
    address:
      expression: address
      human: "Incident Address"
      type: text
    offense_description:
      expression: offense_description
      human: Offense Description
      type: text
    offense_category:
      expression: offense_category
      human: Offense Category
      type: text
    state_offense_code:
      expression: state_offense_code
      human: State Offense Code
      type: text
    incident_timestamp:
      expression: replace(to_char(concat(incident_date, ' ', left(incident_time, 2), ':', right(incident_time, 2), ':00')::timestamp, 'YYYY-MM-DD HH24:MI:SS.000'), ' ', 'T')
      human: Incident Date & Time
      type: calendar_date
    incident_time:
      expression: incident_time
      human: Incident Time (24h)
      type: text
    day_of_week:
      expression: extract(dow from concat(incident_date, ' ', left(incident_time, 2), ':', right(incident_time, 2), ':00')::timestamp) + 1
      human: Day of Week (Sunday is 1)
      type: number
    hour_of_day:
      expression: left(incident_time, 2)::integer
      human: Hour of Day
      type: number
    year:
      expression: right(incident_date, 4)::integer
      human: Year
      type: number
    scout_car_area:
      expression: scout_car_area
      human: Scout Car Area
      type: text
    precinct:
      expression: precinct
      human: Precinct Number
      type: text
    block_id:
      expression: block_id
      human: Census Block GEOID
      type: text
    neighborhood:
      expression: neighborhood
      human: Neighborhood
      type: text
    council_district:
      expression: council_district
      human: Council District
      type: text
    zip_code:
      expression: zip_code
      human: Zip Code
      type: text
    longitude:
      expression: lon
      human: Longitude
      type: number
    latitude:
      expression: lat
      human: Latitude
      type: number
    ibr_date:
      expression: replace(to_char(ibr_date::timestamp, 'YYYY-MM-DD HH24:MI:SS.000'), ' ', 'T')
      human: IBR Report Date
      type: calendar_date
    location:
      expression: CASE WHEN lat is null THEN null ELSE concat('location (', lat, ',', lon, ')') END
      human: Location
      type: location
  row_label: Incident
  time_period:
