name: Blight Violation Notices
dept: Department of Administrative Hearings
schedule: daily

source:
  tidemark:
    type: mssql
    host: 10.213.41.123
    user: 
    pass:
    db: PPLANTST
    tables:
      CASEMAIN: casemain
      CASE_BLD: building_permits
      CASE_PEOPLE: people

