name: Trades Permits
backend: postgres
db: etl
table: bseed_trade_permits
description: >
  Trades permits issued by the City of Detroit Buildings, Safety Engineering & Environmental Department (BSEED).
disclaimer:
website: https://cityofdetroit.github.io/data-resources/datasets/
updates_every: day
license: Public Domain
agency: BSEED
attribution:
source_link:
image:
contact:
  email: iet@detroitmi.gov
  name: IET Team
socrata:
  id: y7ap-7nd5
  view: bseed_trades_permits_socrata
  category: "Property & Parcels"
  tags:
    - permits
    - trades
  row_identifier: unique_id
  permission: private
  # column mapping, used by the create script
  columns:
    unique_id:
      expression: uniq
      human: Unique ID
      type: number
    permit_no:
      expression: permit_no
      human: Permit Number
      type: text
    permit_issued:
      expression: replace(to_char(permit_issued::timestamp, 'YYYY-MM-DD HH24:MI:SS'), ' ', 'T')
      human: Permit Issued
      type: calendar_date
    permit_expire:
      expression: replace(to_char(permit_expire::timestamp, 'YYYY-MM-DD HH24:MI:SS'), ' ', 'T')
      human: Permit Expires
      type: calendar_date
    permit_completed:
      expression: replace(to_char(permit_completed::timestamp, 'YYYY-MM-DD HH24:MI:SS'), ' ', 'T')
      human: Permit Completed
      type: calendar_date
    permit_status:
      expression: permit_status
      human: Permit Status
      type: text
    site_address:
      expression: site_address
      human: Address
      type: text
    between1:
      expression: between1
      human: Between
      type: text
    prc_lot:
      expression: prc_lot
      human: Lot
      type: text
    prc_subdiv:
      expression: prc_subdiv
      human: Subdivision
      type: text
    case_type:
      expression: case_type
      human: Case Type
      type: text
    case_description:
      expression: case_description
      human: Case Description
      type: text
    type_of_use:
      expression: type_of_use
      human: Type Use
      type: text
    type_use_desc:
      expression: description
      human: Type Use Description
      type: text
    permit_type:
      expression: type_of_work
      human: Permit Type
      type: text
    permit_type_desc:
      expression: permit_description
      human: Permit Type Description
      type: text
    fdicn_description:
      expression: fdicn_description
      human: FDICN Description
      type: text
    fee_type:
      expression: fee_type
      human: Fee Type
      type: text
    parcel_size:
      expression: CASE parcel_size WHEN 'NaN' THEN null ELSE parcel_size END
      human: Parcel Size
      type: number
    parcel_cluster_sector:
      expression: parcel_cluster_sector
      human: Sector
      type: text
    parcel_floor_area:
      expression: CASE parcel_floor_area WHEN 'NaN' THEN null ELSE parcel_floor_area END
      human: Parcel Floor Area
      type: number
    parcel_ground_area:
      expression: CASE parcel_ground_area WHEN 'NaN' THEN null ELSE parcel_ground_area END
      human: Parcel Ground Area
      type: number
    prc_aka_address:
      expression: prc_aka_address
      human: AKA Address
      type: text
    seq_no:
      expression: seq_no
      human: Seq No
      type: number
    pcf_amt_due:
      expression: pcf_amt_due
      human: Amount Due
      type: money
    owner_name:
      expression: owner_name
      human: Owner Name
      type: text
    owner_address:
      expression: owner_address1
      human: Owner Address
      type: text
    contractor_name:
      expression: contractor_last_name
      human: Contractor Name
      type: text
    contractor_address:
      expression: contractor_address1
      human: Contractor Address
      type: text
    location:
      expression: >
        CASE 
          WHEN geom is null THEN null 
          ELSE concat('location (', ST_Y(geom), ',', ST_X(geom), ')') 
        END
      human: Permit Location
      type: location
  # not automatable
  row_label: Permit
  time_period: 1/1/2014 - present
  