name: Commercial Demolitions
backend: postgres
db: etl
table: dlba_comm_demos
description: >
  Commercial Demolitions conducted by the DBA and DLBA since 01/01/2014.
disclaimer: >
website: https://cityofdetroit.github.io/data-resources/datasets/
updates_every: day
license:
agency: Detroit Building Authority
attribution:
source_link:
image:
contact:
  email: iet@detroitmi.gov
  name: IET Team
socrata:
  id:
  view: dlba_comm_demos_socrata
  category: "Property & Parcels"
  tags:
    - demolition
    - commercial
  row_identifier: parcel_id
  permission: public
  # column mapping, used by the create script
  columns:
    address:
      expression: address
      human: Address
      type: text
    parcel_id:
      expression: parcel_id
      human: Parcel ID
      type: text
    status:
      expression: status
      human: Status
      type: text
    contractor_name:
      expression: demo_contractor_name
      human: Contractor Name
      type: text
    env_group_number:
      expression: env_group_number
      human: Environmental Survey Group Number
      type: text
    demo_proceed_date:
      expression: replace(to_char(demo_ntp_dt::timestamp, 'YYYY-MM-DD HH24:MI:SS'), ' ', 'T')
      human: Notice to Proceed with Demo Date
      type: calendar_date
    projected_demo_date:
      expression: replace(to_char(demo_proj_demo_dt::timestamp, 'YYYY-MM-DD HH24:MI:SS'), ' ', 'T')
      human: Projected Knock Down Date
      type: calendar_date
    demo_date:
      expression: replace(to_char(knock_start_dt::timestamp, 'YYYY-MM-DD HH24:MI:SS'), ' ', 'T')
      human: Demolished Date
      type: calendar_date
    open_hole_date:
      expression: replace(to_char(open_hole_date::timestamp, 'YYYY-MM-DD HH24:MI:SS'), ' ', 'T')
      human: Open Hole Inspection Approval Date
      type: calendar_date
    winter_grade_date:
      expression: replace(to_char(winter_grade_date::timestamp, 'YYYY-MM-DD HH24:MI:SS'), ' ', 'T')
      human: Winter Grade Inspection Approval Date
      type: calendar_date
    final_grade_date:
      expression: replace(to_char(final_grade_date::timestamp, 'YYYY-MM-DD HH24:MI:SS'), ' ', 'T')
      human: Final Grade Inspection Approval Date
      type: calendar_date
    abatement_cost:
      expression: demo_cost_abatement
      human: Abatement Cost
      type: money
    knock_cost:
      expression: demo_cost_knock
      human: Knock Down Cost
      type: money
    total_cost:
      expression: total_demo_cost
      human: Total Demo Cost
      type: money
    council_district:
      expression: council_district
      human: Council District
      type: text
    neighborhood:
      expression: neighborhood
      human: Neighborhood
      type: text
    latitude:
      expression: latitude
      human: Latitude
      type: number
    longitude:
      expression: longitude
      human: Longitude
      type: number
    location:
      expression: CASE WHEN latitude is null THEN null ELSE concat('location (', latitude, ',', longitude, ')') END
      human: Location
      type: location
  # not automatable
  row_label: Demolition
  time_period: 01/01/2014 - present
