name: 911 Calls for Service (September 20, 2016 - Present)
backend: postgres
db: etl
table: cad
description: >
  This table shows all 911 police emergency response and officer-initiated calls for service in the City of Detroit beginning September 20, 2016. Emergency response calls are the result of people calling 911 to request police services. Officer-initiated calls include traffic stops, street investigations and other policing activities (such as observing crimes in progress) where police officers initiate the response. The table includes all calls taken, dispatch, travel, and total response times for those calls serviced by a police agency. The data also include the responding agency, unit, call type and category of each call.
  Should you have questions about this dataset, you may contact the Commanding Officer of the Detroit Police Department's Crime Intelligence Unit at 313-596-2250, or CrimeIntelligenceBureau@detroitmi.gov.
disclaimer: >
  These data are based upon preliminary information supplied to the Police Department by the reporting parties and are subject to verification. The Detroit Police Department does not guarantee (either expressed or implied) the accuracy, completeness, timeliness, or correct sequencing of the information and the information should not be used for comparison purposes over time. The Detroit Police Department will not be responsible for any error or omission, or for the use of, or the results obtained from the use of this information. All data visualizations on maps should be considered approximate and attempts to derive specific addresses are strictly prohibited.
  The Detroit Police Department is not responsible for the content of any off-site pages that are referenced by or that reference this web page other than an official City of Detroit or Detroit Police Department web page. The user specifically acknowledges that the Detroit Police Department is not responsible for any defamatory, offensive, misleading, or illegal conduct of other users, links, or third parties and that the risk of injury from the foregoing rests entirely with the user. Any use of the information for commercial purposes is strictly prohibited. The unauthorized use of the words Detroit Police Department, "Detroit Police," or any colorable imitation of these words or the unauthorized use of the Detroit Police Department logo is unlawful. This web page does not, in any way, authorize such use.
website: https://cityofdetroit.github.io/data-resources/datasets/
updates_every: day
license:
agency: Detroit Police Department
attribution:
source_link:
image:
contact:
  email: crimeintelligencebureau@detroitmi.gov
  name: Crime Intelligence Unit
socrata:
  id: wgv9-drfc
  view: cad_socrata
  category: Public Safety
  tags:
    - police
    - dpd
    - "911"
    - "calls for service"
  row_identifier: incident_id
  permission: private
  # column mapping, used by the create script
  columns:
    incident_id:
      expression: inci_id
      human: Incident ID
      type: text
    agency:
      expression: agency
      human: Agency
      type: text
    incident_address:
      expression: anonymized_addr
      human: Incident Address
      type: text
    zip_code:
      expression: zip
      human: Zip Code
      type: text
    priority:
      expression: priority
      human: Priority
      type: number
    callcode:
      expression: callcode
      human: Call Code
      type: text
    calldescription:
      expression: calldescription
      human: Call Description
      type: text
    category:
      expression: category
      human: Category
      type: text
    call_timestamp:
      expression: replace(to_char(concat(calldate, ' ', dp_calltime)::timestamp, 'YYYY-MM-DD HH24:MI:SS'), ' ', 'T')
      human: Call Time
      type: calendar_date
    time_of_call:
      expression: dp_calltime
      human: Time of Call
      type: text
    precinct_sca:
      expression: '"precinctSCA"'
      human: Precinct/Scout Car Area
      type: text
    respondingunit:
      expression: respondingunit
      human: Responding Unit
      type: text
    officerinitiated:
      expression: officerinitiated
      human: Officer Initiated
      type: text
    intaketime:
      expression: replace(intaketime, ',', '')
      human: Intake Time
      type: number
    dispatchtime:
      expression: replace(dispatchtime, ',', '')
      human: Dispatch Time
      type: number
    traveltime:
      expression: replace(traveltime, ',', '')
      human: Travel Time
      type: number
    totalresponsetime:
      expression: replace(totalresponsetime, ',', '')
      human: Total Response Time
      type: number
    time_on_scene:
      expression: replace(timeonscene, ',', '')
      human: Time On Scene
      type: number
    totaltime:
      expression: replace(totaltime, ',', '')
      human: Total Time
      type: number
    neighborhood:
      expression: neighborhood
      human: Neighborhood
      type: text
    block_id:
      expression: block_id
      human: Census Block GEOID
      type: text
    council_district:
      expression: council_district
      human: Council District
      type: text
    longitude:
      expression: lon
      human: Longitude
      type: number
    latitude:
      expression: lat
      human: Latitude
      type: number
    location:
      expression: CASE WHEN lat is null THEN null ELSE concat('location (', lat, ',', lon, ')') END
      human: Incident Location
      type: location
  # not automatable
  row_label: Incident
  time_period:
